### ISSUE TITLE
subprocess.CalledProcessError: Command '['tput', 'sitm']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by wangxinhe2006** [IngoHeimbach/simple-term-menu#2]
macOS Catalina (10.15.3)
Python 3.7.7
iTerm 3.3.7
```
bash-3.2$ simple-term-menu 1 2 3
Traceback (most recent call last):
  File "/Library/Python/3.7/bin/simple-term-menu", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/3.7/lib/python/site-packages/simple_term_menu.py", line 295, in main
    cycle_cursor=args.cycle,
  File "/Library/Python/3.7/lib/python/site-packages/simple_term_menu.py", line 85, in __init__
    self._init_terminal_codes()
  File "/Library/Python/3.7/lib/python/site-packages/simple_term_menu.py", line 96, in _init_terminal_codes
    for codename in cls._codenames
  File "/Library/Python/3.7/lib/python/site-packages/simple_term_menu.py", line 96, in <dictcomp>
    for codename in cls._codenames
  File "/Library/Python/3.7/lib/python/site-packages/simple_term_menu.py", line 109, in _query_terminfo_database
    return str(subprocess.check_output(["tput"] + capname.split(), universal_newlines=True))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tput', 'sitm']' returned non-zero exit status 1.
```

**Comment by IngoHeimbach** [comment]
Hey, thanks for the bug report. It seems that the macOS terminal has no support for italics and my script did not handle that case. It should be fixed in version v0.4.2 (already uploaded to PyPI). Could you please test again?

**Comment by wangxinhe2006** [comment]
Upgraded to v0.4.2, but I stiil got `subprocess.CalledProcessError`.
I've tried in both `Terminal.app` and `iTerm 3.3.7`.

**Comment by IngoHeimbach** [comment]
Do you get the exact same error as before?

**Comment by wangxinhe2006** [comment]
Oops, sorry. It works now. I installed it in the wrong environment.

**Comment by IngoHeimbach** [comment]
No problem, thanks for testing :+1:

**Comment by wangxinhe2006** [comment]
Thanks a lot. BTW, I would like to ask if it works in Windows.

**Comment by IngoHeimbach** [comment]
I did not test it, but I don't think so. It should only work in a WSL terminal. For Windows, the whole terminal code part needs to be extended.
