### ISSUE TITLE
simple-term-menu not work on Windows

### ISSUE THREAD

**Issue by jDan735** [IngoHeimbach/simple-term-menu#5]
# System
| Parameter | Info                    |
|-----------|-------------------------|
| OS        | Win7 SP1 x86            |
| Python    | Python 3.8.3            |
| Pip       | Pip 20.1.1              |
# Steps to reproduce
1. `pip install simple-term-menu`
2. run this code:
```python
from simple_term_menu import TerminalMenu

terminal_menu = TerminalMenu(["entry 1", "entry 2", "entry 3"])
terminal_menu.show()
```
# Output
```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "H:\github\simple-term-menu\simple_term_menu.py", line 7, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'
```

**Comment by IngoHeimbach** [comment]
Thanks for trying simple-term-menu. Currently, only Linux and macos are supported. Windows needs completely different terminal handling code. That is also the reason why `termios` is not available on Windows (on Unix-like systems it is part of the Python standard library).

**Comment by IngoHeimbach** [comment]
Is using [Cygwin](https://www.cygwin.com) maybe an option for you?

**Comment by jDan735** [comment]
Possible. simple-term-menu started in msys32, also this must work in wsl

**Comment by IngoHeimbach** [comment]
The next release will at least throw a more descriptive exception for non-supported platforms.

**Comment by buanzo** [comment]
Just to mention it works fine on wsl as @jDan735 indicated.

![image](https://user-images.githubusercontent.com/553167/107998646-58dbb900-6fc4-11eb-94c7-cce185b8b0ff.png)

**Comment by tmkkcc** [comment]
Will this be fixed soon? Are there alternatives to this ?

**Comment by IngoMeyer441** [comment]
Windows terminals need completely different terminal handling code so quite a lot of work has to be done first. I think it would be best to split simple-term-menu in a platform dependent and a platform independent part so the right terminal backend code can be loaded if on Unix or Windows. However:

- I don't know if a Windows terminal supports all features simple-term-menu uses in Unix environments.
- I definitely need help here because I am not very familiar with Windows programming.

@tmkkcc Maybe bullet could be the right choice for you. There is a [open PR for adding Windows support](https://github.com/bchao1/bullet/pull/79).

**Comment by buanzo** [comment]
I use it within Microsoft Terminal (the one from the app store), under wsl2
and it runs wonderfully.

I wouldn't be so sure under legacy terminal, but I might be able to help
you test, develop.

**Comment by wnhrt** [comment]
I have played around a bit in the last two days and got at least the basic basic functions in 'Windows Terminal' to work:
![image](https://user-images.githubusercontent.com/70302993/129072038-e94865f5-093a-4b9a-a310-c0324ec563b8.png)
![image](https://user-images.githubusercontent.com/70302993/129072515-11b97dd9-e68f-4f4f-85fe-ee61611d6674.png)

At first sight it looks like entry selection, colors, preview and search (just couldn't get `<backspace>` to work as expected) could work fine without too many changes.

I have close to no knowledge about Windows Terminal and CMD handling, but I figured following key points might be quiet challenging to implement:
- window resize event
- unicode / wcswidth (didn't find any easy alternative implemented in Windows) > https://github.com/jquast/wcwidth

and most likely some other things and edge cases, which I have not considered yet. Without external dependencies, the amount of code is likely to grow a lot. I have also used some shortcuts which could benefit from a proper implementation (e.g. use of sys.stdin/out, instat of a proper stream handle).

But perhaps I have overlooked some simpler solutions.

**Comment by wnhrt** [comment]
Sure thing 😃
https://github.com/wnhrt/simple-term-menu/pull/1/commits/9f65d656d182ff4e648c8ca002a21fe59bd5869d
(Your recent commit about multiselect slipped with in)

I could get backspace to work (used the wrong key code) and enable VT100 mode in CMD.exe.
![image](https://user-images.githubusercontent.com/70302993/129117808-d09bb7db-88e0-4d53-b314-d3583c24c658.png)

Variable length unicode symbols and resize of the window still cause problems and I didn't test key combinations, like Alt+X or Ctrl+X.

I reused most of your code. Design wise it might be sensible to create Windows-specific functions, e.g. for _query_terminfo_database.

**Comment by IngoMeyer441** [comment]
If it is possible to display Unicode characters, the Unicode box characters should also work. Didn't know that the legacy terminal supports Unicode characters.

**Comment by wnhrt** [comment]
I guess it does not. It uses [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252). But you are right, it luckily supports box characters :)

I made a pull request, which also includes a fix to use them.

**Comment by IngoMeyer441** [comment]
The [wcwidth](https://github.com/jquast/wcwidth) module could become an optional dependency for Windows (for example, by installing it with `pip install simple-term-menu[wcwidth]`). If it is not installed, `simple-term-menu` could fall back to the `len` function, so people (especially Unix users) are not forced to install any dependency.

**Comment by nitsuaustin11** [comment]
not sure if this helps. but i just installed the lynux terminal and it all works fine. couldnt run anything before.

just ran "wsl --install" in my terminal. i think as admin. and then restarted pc.

**Comment by cornradio** [comment]
is there any thing like simple-term-menu work on windows?
i just need some basic funcion like short cut and choosing item!

**Comment by cornradio** [comment]
since there is not any progress about supporting windows, i made this if any one need ! [dumb_menu ](https://github.com/cornradio/dumb_menu)

**Comment by Abeautifulsnow** [comment]
[python-inquirer](https://github.com/magmax/python-inquirer) is also a good choice(supports cross-platform and single/multiple selection, etc). Hope it will save your life.

**Comment by ryan-cpi** [comment]
Has there been any movement on supporting Windows? This means that I'm not able to use simple-term-menu in some of our Python libraries we publish to pypi as not all users would be supported.

**Comment by IngoMeyer441** [comment]
Currently, I cannot spend any time on implementing Windows support. There is some work done on initial Windows support (#34, thanks @wnhrt), but there is still some work to do to separate Windows code from Unix and to implement missing features. Unfortunately, terminal handling on Windows is completely different from Unix.

**Comment by buanzo** [comment]
I will try to work on windows support. I use the this library under wslg
using Microsoft terminal, and native Linux.

**Comment by brandon-fryslie** [comment]
Microsoft added WSL so Windows users can run standard software like everyone else.  It's hard to understand why people would wait years rather than install and use the thing Microsoft provided for this purpose.  It's not perfect but at least it's Ubuntu, pretty user friendly and straightforward.
